version: '3.9'

services:
  db:
    mem_limit: 2048m
    image: mariadb:${MARIADB_VERSION}
    environment:
      MARIADB_DATABASE: $MYSQL_DATABASE
      MARIADB_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MARIADB_USER: $MYSQL_USER
      MARIADB_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:$PHPMYADMIN_VERSION
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    restart: unless-stopped

  wordpress:
    image: wordpress:$WORDPRESS_VERSION
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - db
    ports:
      - ${WORDPRESS_PORT}:80
    restart: unless-stopped

netwowks:
  db:
